function greWords() {

a = a.concat([["superfluous", "(a.) unnecessary; extra"],
["diminutive", "(a.) smaller than average"],
["tedious", "(a.) boring, repetitive and tiresome"],
["caustic", "(a.) harsh or corrosive"],
["destitute", "(a.) poor, living in poverty"],
["bestial", "(a.) showing a lack of human sensibility; like an animal"],
["incredulous", "(a.) skeptical"],
["cerebral", "(a.) relating to the brain; intellectual"],
["sedentary", "(a.) characterized by sitting"],
["stolid", "(a.) unemotional, not easily excited"],
["inveterate", "(a.) firmly established in a habit"],
["nebulous", "(a.) unclear or vague"],
["affable", "(a.) friendly, good-natured"],
["derogatory", "(a.) belittling; uncomplimentary"],
["sinuous", "(a.) full of curves; twisting and turning"],
["clandestine", "(a.) done secretly"],
["determinate", "(a.) having distinct limits"],
["fallacious", "(a.) misleading; based on incorrect information"],
["overweening", "(a.) arrogant; excessive"],
["stagnant", "(a.) motionless, uncirculating"],
["impetuous", "(a.) characterized by excessive haste and lack of deliberation; moving with great force and energy"],
["eccentric", "(a.) unconventional or unusual"],
["sylvan", "(a.) pertaining to or characteristic of a forest or woodland"],
["insidious", "(a.) slowly and subtly harmful"],
["laconic", "(a.) using few words"],
["onerous", "(a.) burdensome; oppressive"],
["apocryphal", "(a.) of questionable authenticity"],
["ingenuous", "(a.) innocent, naive; honest"],
["winsome", "(a.) charming"],
["ephemeral", "(a.) lasting a short time"],
["garrulous", "(a.) talking too much; wordy"],
["inchoate", "(a.) just beginning to develop; lacking structure or organization"],
["immaculate", "(a.) perfectly clean, pure; without faults"],
["prodigal", "(a.) extravagantly wasteful"],
["perfunctory", "(a.) done hastily and without attention to detail; indifferent"],
["perfidious", "(a.) intending to betray"],
["choleric", "(a.) easily angered, irascible"],
["emollient", "(a.; n.) soothing; a soothing substance"],
["pedantic", "(a.) overly concerned with formal rules and details"],
["fatuous", "(a.) stupid or foolish in a self-satisfied way"],
["acrid", "(a.) sharp; bitter; foul smelling"],
["insipid", "(a.) dull; lacking flavor"],
["decorous", "(a.) characterized by proper manners and conduct"],
["pellucid", "(a.) transparent; clear in meaning"],
["obsequious", "(a.) attempting to win favor by flattery and submissiveness, fawning"],
["authoritarian", "(a.; n.) demanding obedience; a dictator"],
["exigent", "(a.) critical, requiring immediate action"],
["estimable", "(a.) deserving of respect"],
["dauntless", "(a.) fearless; not discouraged"],
["imminent", "(a.) about to happen"],
["pertinacious", "(a.) holding firmly to a course of action or a set of beliefs"],
["captious", "(a.) overly critical and complaining"],
["ineffable", "(a.) impossible to describe in words"],
["credulous", "(a.) too trusting; gullible"],
["ostensible", "(a.) represented or appearing in one way, but not necessarily that way in reality"],
["deleterious", "(a.) harmful; hurtful; noxious"],
["mercurial", "(a.) tending to change mood or behavior suddenly and unpredictably"],
["saturnine", "(a.) melancholy, gloomy, morose"],
["esoteric", "(a.) known or understood by only a few"],
["taciturn", "(a.) reserved and generally quiet"],
["sedulous", "(a.) working diligently and carefully"],
["hermetic", "(a.) sealed tightly; protected from outside influence"],
["sublime", "(a.) beautiful, heavenly, inspiring awe"],
["effervescent", "(a.) bubbling, excited"],
["dilatory", "(a.) intended to delay"],
["gregarious", "(a.) outgoing, sociable"],
["verdant", "(a.) green with vegetation; green; inexperienced"],
["tortuous", "(a.) highly intricate; winding"],
["restive", "(a.) hard to manage"],
["aesthetic", "(a.) of beauty; pertaining to taste in art and beauty"],
["turgid", "(a.) bombastic; swollen"],
["salacious", "(a.) characterized by lust"],
["diffident", "(a.) lacking self-confidence"],
["brusque", "(a.) abrupt or curt in manner or speech"],
["artful", "(a.) not straightforward or candid; crafty"],
["soporific", "(a.) causing sleep or lethargy"],
["unwonted", "(a.) not usual or expected; not in character"],
["perspicacious", "(a.) keen in observation and understanding"],
["moribund", "(a.) dying, on the way out"],
["histrionic", "(a.) pertaining to actors and their techniques; theatrical, artificial, melodramatic"],
["indolent", "(a.) lazy"],
["impudent", "(a.) showing casual disrespect"],
["torpid", "(a.) sluggish, lacking energy"],
["furtive", "(a.) done secretly"],
["indigent", "(a.) needy, impoverished"],
["hapless", "(a.) having persistent bad luck"],
["adventitious", "(a.) associated with something by chance and not an integral part"],
["bucolic", "(a.) of the countryside or country life"],
["officious", "(a.) annoyingly eager to help"],
["wizened", "(a.) dry, shrunken, and wrinkled"],
["chary", "(a.) extremely cautious or hesitant"],
["penitent", "(a.; n.) regretful for one's sins; one who is sorry for wrongdoing"],
["profligate", "(a.) recklessly wasteful; having low morals"],
["refulgent", "(a.) shining, radiant"],
["felicitous", "(a.) appropriate; happy"],
["fastidious", "(a.) demanding, concerned with every detail"],
["macabre", "(a.) gruesome; distressing"],
["itinerant", "(a.; n.) moving around to find work; a person who travels from place to place"],
["plenary", "(a.) attended by all members; complete in all aspects"],
["quotidian", "(a.) ordinary, mundane"],
["trenchant", "(a.) sharp, incisive; forceful, effective"],
["pusillanimous", "(a.) contemptibly cowardly"],
["rebarbative", "(a.) serving or tending to repel"],
["incendiary", "(a.; n.) intending or designed to start fires; tending to stir up strife; one who sets fires or causes strife"],
["diurnal", "(a.) active during the daytime"],
["specious", "(a.) plausible but false"],
["desultory", "(a.) passing aimlessly from one thing to another; random"],
["halcyon", "(a.) calm, peaceful; prosperous"],
["jejune", "(a.) lacking in nutritive value; uninteresting; juvenile"],
["bourgeois", "(a.) conforming to standards and conventions of the middle class"],
["ersatz", "(a.) artificial and inferior"],
["recumbent", "(a.) lying down"],
["prodigious", "(a.) enormous; exceptional"],
["sententious", "(a.) overly moralizing"],
["meretricious", "(a.) attractive in a superficial manner but without real value"],
["esurient", "(a.) very hungry or greedy"],
["redolent", "(a.) suggestive or reminiscent of something; having an aroma"],
["plaintive", "(a.) expressive of sorrow or woe"],
["abstruse", "(a.) difficult to understand"],
["anterior", "(a.) near the front or head of the body"],
["prurient", "(a.) characterized by lust"],
["peremptory", "(a.) dictatorial"],
["inexorable", "(a.) impossible to stop"],
["moot", "(a.) open to argument; irrelevant"],
["truculent", "(a.) aggressively defiant or hostile"],
["declamatory", "(a.) lofty in style, bombastic"],
["turbid", "(a.) muddy; cloudy"],
["venal", "(a.) capable of being bribed; corrupt"],
["bromidic", "(a.) dull, unoriginal"],
["apocalyptic", "(a.) predicting or involving widespread destruction"],
["urbane", "(a.) sophisticated and refined"],
["fecund", "(a.) fruitful in offspring or vegetation; intellectually productive"],
["picayune", "(a.) having little value or importance"],
["maudlin", "(a.) silly and overly sentimental"],
["seraphic", "(a.) like an angel"],
["judicious", "(a.) having wisdom or discretion"],
["phlegmatic", "(a.) showing little emotion"],
["monolithic", "(a.) massive and uniform"],
["tantamount", "(a.) equivalent to"],
["sanguine", "(a.) cheerful and optimistic"]]);

n = n.concat([["litany", "(n.) a prayer or chant; a long list"],
["caprice", "(n.) a sudden unpredictable or whimsical change"],
["couture", "(n.) fashion design; fashionable clothing"],
["peregrination", "(n.) the act of traveling; an excursion"],
["anecdote", "(n.) a short personal account of an event"],
["quandary", "(n.) a state of perplexity; a difficult situation"],
["heresy", "(n.) a belief that rejects the accepted tenets of a religion"],
["acrimony", "(n.) sharpness or bitterness in language or manner"],
["husbandry", "(n.) management of resources, especially in agriculture"],
["censure", "(n.; v.) an expression of disapproval; to criticize or disapprove of"],
["cloister", "(n.) a tranquil and secluded place"],
["derision", "(n.) the act of mocking; ridicule, mockery"],
["archaism", "(n.) an old expression or practice that is no longer used"],
["deference", "(n.) courtesy, respect; submission to another person's opinion or wishes"],
["paucity", "(n.) scarcity"],
["accolade", "(n.) a sign of approval or respect"],
["accomplice", "(n.) a partner; a partner-in-crime"],
["legerdemain", "(n.) a display of cleverness, especially to deceive others"],
["potentate", "(n.) a powerful ruler; an important person"],
["carping", "(n.) petty nagging criticism"],
["sacrilege", "(n.) improper or disrespectful treatment of something sacred"],
["idiosyncrasy", "(n.) any personal peculiarity, mannerism"],
["tableau", "(n.) a picturesque display"],
["iconoclast", "(n.) somebody who challenges established beliefs, customs, and values"],
["loquacity", "(n.) the quality of being wordy and talkative"],
["coterie", "(n.) a group of people with a common interest"],
["cacophony", "(n.) an unpleasant noise"],
["opprobrium", "(n.) a state of shame or disgrace; scorn, contempt"],
["penchant", "(n.) a strong liking"],
["pariah", "(n.) one who is rejected by a social group"],
["duress", "(n.) imprisonment; the use of threats"],
["gamin", "(n.) a child who roams the streets"],
["charlatan", "(n.) one who feigns knowledge or ability; an imposter"],
["foible", "(n.) a minor flaw or failing"],
["debutante", "(n.) a young woman being introduced to society"],
["remuneration", "(n.) a payment; the act of paying"],
["cynic", "(n.) one who distrusts human nature"],
["progeny", "(n.) descendants, offspring; followers"],
["inception", "(n.) the beginning of something"],
["blandishment", "(n.) anything designed to flatter or coax"],
["neologism", "(n.) a newly invented word or phrase"],
["aberration", "(n.) something different from the usual or normal"],
["sepulchre", "(n.) a burial chamber"],
["martinet", "(n.) somebody who demands exact conformity to rules"],
["torpor", "(n.) a lack of energy or vigor, lethargy"],
["platitude", "(n.) a trite statement"],
["affectation", "(n.) unnatural behavior intended to impress"],
["elegy", "(n.) a sorrowful poem or speech"],
["dilettante", "(n.) an amateur"],
["aperture", "(n.) an opening, gap, hole"],
["progenitor", "(n.) an ancestor in the direct line"],
["veracity", "(n.) truthfulness"],
["paroxysm", "(n.) a sudden uncontrollable spasm"],
["mainstay", "(n.) somebody or something that plays an important role"],
["promiscuity", "(n.) the practice of indulging in casual sexual relations"],
["sycophant", "(n.) a person who serves and flatters someone powerful for personal gain"],
["epigram", "(n.) a witty saying"],
["distaff", "(n.) work or other matters regarded as the concern of women"],
["celerity", "(n.) swiftness"],
["consanguinity", "(n.) a relationship by blood"],
["largesse", "(n.) generosity in giving"],
["suppliant", "(n.; a.) one who makes a request humbly and earnestly; asking humbly and earnestly"],
["acumen", "(n.) mental sharpness"],
["guile", "(n.) the use of tricks to deceive someone"],
["encumbrance", "(n.) a burden"],
["panegyric", "(n.) a formal expression of praise"],
["antipathy", "(n.) intense hatred"],
["recidivism", "(n.) the act of returning to a life of crime"],
["compunction", "(n.) feelings of shame and regret"],
["scion", "(n.) a young descendant or heir"],
["abeyance", "(n.) suspension of activity"],
["harbinger", "(n.) something that foreshadows a future event"],
["reticence", "(n.) the trait of being uncommunicative"],
["propinquity", "(n.) the property of being close together"],
["insolence", "(n.) disrespect, rudeness"],
["kismet", "(n.) fate or destiny"],
["nostrum", "(n.) a hypothetical cure-all that may have no true efficacy"],
["perquisite", "(n.) a privilege that goes along with a job"],
["dudgeon", "(n.) a fit of anger"],
["anachronism", "(n.) something from a different historical period of time"],
["coda", "(n.) the closing section of a musical composition"],
["effigy", "(n.) a crude image of a despised person"],
["welter", "(n.) a confused multitude of things"],
["countenance", "(n.; v.) facial expression; composure; to tolerate or support"],
["raillery", "(n.) friendly teasing"],
["peripatetic", "(n.; a.) a worker who travels around; traveling, especially for work"],
["raconteur", "(n.) a skilled story-teller"],
["zenith", "(n.) the highest point"],
["gaucherie", "(n.) social awkwardness"],
["raiment", "(n.) clothing, garments"],
["effluent", "(n.) liquid waste; a stream"],
["cabal", "(n.) a group of people with secret purposes and meetings"],
["riposte", "(n.) a quick and witty reply"],
["hedonist", "(n.) a person who lives for pleasure"],
["petulance", "(n.) the quality of being easily irritated"],
["fealty", "(n.) allegiance or loyalty"],
["contusion", "(n.) a bruise; an injury where the skin is not broken"],
["gambit", "(n.) a maneuver in a game or conversation used to secure an advantage"],
["zephyr", "(n.) a slight breeze"],
["rampart", "(n.) a fortification"],
["nadir", "(n.) the lowest point"],
["canard", "(n.) a false rumor"],
["cynosure", "(n.) the center of attraction; something that serves to guide or direct"],
["mendacity", "(n.) the tendency to be untruthful"],
["detritus", "(n.) debris or discarded material"],
["apotheosis", "(n.) a paragon; elevation to divine status"],
["apothegm", "(n.) a short instructive saying"],
["pedant", "(n.) somebody too concerned with rules and details"],
["ostentation", "(n.) conspicuous display intended to impress others"],
["magnate", "(n.) a powerful business-person"],
["expurgation", "(n.) the removal of indecent passages from a text"],
["fracas", "(n.) a noisy quarrel"],
["mettle", "(n.) strength of character, determination"],
["homily", "(n.) a sermon"],
["shibboleth", "(n.) a slogan"],
["effrontery", "(n.) an arrogant attitude or behavior that is insulting to others"],
["sophistry", "(n.) a flawed argument"],
["luminary", "(n.) an important or famous person"],
["perfidy", "(n.) betrayal or deceit"],
["sopor", "(n.) a deep sleep"],
["badinage", "(n.) light and playful conversation"],
["fustian", "(n.) pompous or pretentious speech, bombast"],
["proclivity", "(n.) a natural inclination"],
["proletariat", "(n.) the working class"],
["rapprochement", "(n.) reconciliation"],
["philistine", "(n.) someone who is uncultured and indifferent to intellectual matters"],
["neophyte", "(n.) a beginner"],
["philippic", "(n.) a violent verbal attack"],
["alacrity", "(n.) liveliness and eagerness"],
["toady", "(n.) a person who tries to please others to gain a personal advantage"],
["encomium", "(n.) a formal expression of praise, a eulogy"],
["threnody", "(n.) a speech of lament for the dead"],
["mercenary", "(n.) a hired soldier; someone motivated only by money"],
["mendicant", "(n.) a beggar"],
["discernment", "(n.) an ability to make good judgments"],
["anomaly", "(n.) something that is unusual or unexpected"],
["travesty", "(n.) a distorted representation of something"],
["animus", "(n.) a feeling of hostility; motivation"],
["patrician", "(n.) a member of the aristocracy"],
["peccadillo", "(n.) a minor offense"]]);

v = v.concat([["peculate", "(v.) to steal another's money or property"],
["ameliorate", "(v.) to improve or make better"],
["burgeon", "(v.) to grow or develop quickly"],
["heed", "(v.) to pay close attention to"],
["vindicate", "(v.) to show to be right"],
["recant", "(v.) to withdraw a previously held statement of belief"],
["deprecate", "(v.) to express disapproval of"],
["synthesize", "(v.) to combine various components into a new whole"],
["incarcerate", "(v.) to put somebody in prison"],
["placate", "(v.) to make somebody less angry"],
["refurbish", "(v.) to restore something to a better condition"],
["vilify", "(v.) to spread negative information about"],
["plumb", "(v.) to measure the depth of something"],
["mandate", "(v.) to order something officially"],
["commiserate", "(v.) to show sympathy for"],
["comport", "(v.) to behave well or properly"],
["condescend", "(v.) to treat others as socially or intellectually inferior"],
["vex", "(v.) to annoy"],
["impede", "(v.) to be a hindrance or obstacle to"],
["entreat", "(v.) to ask earnestly"],
["sanction", "(v.) to give authority or permission"],
["cavort", "(v.) to frolic"],
["confound", "(v.) to lump together, causing confusion; to damn"],
["obviate", "(v.) to do away with or make unnecessary; to prevent"],
["abdicate", "(v.) to give up a duty or a position"],
["disseminate", "(v.) to distribute or spread something, especially information"],
["conjure", "(v.) to summon; to bring into being as if by magic"],
["inculcate", "(v.) to teach by frequent repetition"],
["abscond", "(v.) to leave secretly"],
["consummate", "(v.; a.) to bring to a state of completion or perfection; complete or perfect"],
["forbear", "(v.) to not do something"],
["subjugate", "(v.) to bring somebody under the control of another"],
["occlude", "(v.) to stop up; to cut off the flow"],
["obfuscate", "(v.) to make unclear"],
["attenuate", "(v.) to make thin or slender; to weaken or lessen in intensity"],
["inure", "(v.) to cause to accept or become hardened to, to habituate"],
["corroborate", "(v.) to support with evidence or authority"],
["burnish", "(v.) to polish by rubbing"],
["pervade", "(v.) to spread throughout"],
["fleece", "(v.) to defraud or swindle"],
["expostulate", "(v.) to attempt to dissuade somebody from doing something"],
["rebuff", "(v.) to snub, drive away, reject"],
["desiccate", "(v.) to dry out"],
["ossify", "(v.) to harden into bone"],
["flaunt", "(v.) to display proudly"],
["impugn", "(v.) to criticize or cast doubt on"],
["polarize", "(v.) to cause a division of opinion between groups"],
["brook", "(v.) to tolerate something or somebody unpleasant"],
["dissemble", "(v.) to pretend; to hide under a false appearance"],
["espouse", "(v.) to support or adopt"],
["ingratiate", "(v.) to seek to please somebody to gain favor"],
["descant", "(v.) to talk or write at length"],
["beget", "(v.) to make children; to cause"],
["venerate", "(v.) to respect and honor"],
["improvise", "(v.) to perform without preparation"],
["flout", "(v.) to treat with contemptuous disregard"],
["expedite", "(v.) to speed up the progress of"],
["temporize", "(v.) to stall or act evasively in order to gain time"],
["reconnoiter", "(v.) to explore an area and gather information, especially about enemy forces"],
["goad", "(v.) to urge; to give courage to"],
["augur", "(v.) to indicate by signs; to predict from an omen"],
["immure", "(v.) to imprison, to incarcerate"],
["expropriate", "(v.) to take arbitrarily or by force"],
["repine", "(v.) to express discontent"],
["enervate", "(v.) to weaken"],
["denigrate", "(v.) to defame, to blacken or sully; to belittle"],
["exonerate", "(v.) to pronounce not guilty"],
["abnegate", "(v.) to renounce something"],
["eschew", "(v.) to avoid, shun, keep away from"],
["oscillate", "(v.) to move from side to side regularly"],
["prevaricate", "(v.) to be intentionally ambiguous or unclear in order to mislead"],
["reciprocate", "(v.) to give back in return"],
["promulgate", "(v.) to proclaim or issue officially"],
["excoriate", "(v.) to criticize severely"],
["disabuse", "(v.) to free from error"],
["accrete", "(v.) to grow together"],
["abrogate", "(v.) to formally revoke an agreement or contract"],
["demur", "(v.; n.) to object; an objection"],
["lionize", "(v.) to treat as a celebrity"],
["palliate", "(v.) to treat the symptoms"],
["importune", "(v.) to trouble with demands; to beg for insistently"],
["proscribe", "(v.) to outlaw"],
["imprecate", "(v.) to pray for evil; to invoke a curse"],
["emulate", "(v.) to try to equal somebody or something"],
["winnow", "(v.) to sift through removing what is unwanted and keeping what is desirable"],
["perjure", "(v.) to tell a lie in a court of law"],
["descry", "(v.) to catch sight of"],
["sequester", "(v.) to separate or segregate"],
["forfend", "(v.) to prevent something from happening"],
["hector", "(v.) to bully"],
["cower", "(v.) to huddle and tremble"],
["cloy", "(v.) to sicken somebody with too much of a good thing"],
["pillory", "(v.; n.) to punish in public; a device for public punishment"],
["defenestrate", "(v.) to throw out of a window"],
["malinger", "(v.) to pretend to be ill in order to avoid a responsibility"],
["patronize", "(v.) to do business with; to treat somebody as unintelligent"],
["indemnify", "(v.) to insure against or pay for loss or damage"],
["proselytize", "(v.) to try to convert somebody"],
["bereave", "(v.) to deprive through death"],
["simper", "(v.) to smile artificially"],
["vitiate", "(v.) to make something ineffective; to degrade"],
["enfranchise", "(v.) to grant privileges of citizenship, especially the right to vote"],
["bowdlerize", "(v.) to modify by removing inappropriate sections from a text"],
["galvanize", "(v.) to stimulate as if by electric shock; to excite"],
["propitiate", "(v.) to win somebody's favor"],
["extrapolate", "(v.) to guess at general conclusions based on what is already known"],
["capitulate", "(v.) to surrender; to give up or give in"],
["efface", "(v.) to remove; to be inconspicuous"],
["philander", "(v.) to have amorous affairs"],
["distend", "(v.) to swell up"],
["convalesce", "(v.) to recover from an illness"],
["decamp", "(v.) to leave suddenly or secretly"],
["litigate", "(v.) to engage in legal proceedings"],
["expatriate", "(v.; n.) to expel from a country; to move away from one's home country; one who has left his country"],
["discomfit", "(v.) to cause to lose one's composure"],
["adulate", "(v.) to praise too greatly"],
["engender", "(v.) to create; to arise or come into existence"],
["rarefy", "(v.) to make something less dense; to refine"],
["garner", "(v.) to gather or gain something"],
["remonstrate", "(v.) to argue strongly against some action"],
["arrogate", "(v.) to claim or take without right"],
["cajole", "(v.) to coax with insincere talk"],
["apotheosize", "(v.) to glorify; to make into a god"],
["slough", "(v.; n.) to discard; to ignore; a swamp"],
["gainsay", "(v.) to oppose; to claim that something is false"],
["discourse", "(v.) to communicate in an orderly fashion"],
["condone", "(v.) to excuse or make allowances for"],
["undermine", "(v.) to weaken gradually; to discredit"],
["forsake", "(v.) to withdraw support"],
["fulminate", "(v.) to criticize severely"],
["requite", "(v.) to pay something back for a service or a kindness"],
["equivocate", "(v.) to be deliberately unclear or ambiguous"],
["assuage", "(v.) to relieve; ease; make less severe"],
["nullify", "(v.) to declare invalid"],
["cavil", "(v.) to raise trivial objections; to bicker"],
["calumniate", "(v.) to slander"],
["extemporize", "(v.) to perform without preparation"],
["exculpate", "(v.) to clear from blame"],
["vacillate", "(v.) to be undecided; to sway back and forth"],
["presage", "(v.) to foretell something"]]);

}


function satWords() {

a = a.concat([["fecund", "(a.) fruitful in offspring or vegetation; intellectually productive"],
["truculent", "(a.) aggressively defiant or hostile"],
["prurient", "(a.) characterized by lust"],
["monolithic", "(a.) massive and uniform"],
["apocalyptic", "(a.) predicting or involving widespread destruction"],
["incendiary", "(a.; n.) intending or designed to start fires; tending to stir up strife; one who sets fires or causes strife"],
["trenchant", "(a.) sharp, incisive; forceful, effective"],
["specious", "(a.) plausible but false"],
["halcyon", "(a.) calm, peaceful; prosperous"],
["meretricious", "(a.) attractive in a superficial manner but without real value"],
["adventitious", "(a.) associated with something by chance and not an integral part"],
["bucolic", "(a.) of the countryside or country life"],
["officious", "(a.) annoyingly eager to help"],
["furtive", "(a.) done secretly"],
["plenary", "(a.) attended by all members; complete in all aspects"],
["concise", "(a.) using few words; brief"],
["noxious", "(a.) harmful to one’s health"],
["lethargic", "(a.) lazy; passive"],
["indifferent", "(a.) lacking interest; without a preference"],
["inane", "(a.) silly; insubstantial"],
["inevitable", "(a.) impossible to avoid or prevent"],
["blasphemous", "(a.) disrespectful of sacred things"],
["bombastic", "(a.) displaying exaggerated self-importance"],
["unruly", "(a.) disobedient"],
["eminent", "(a.) standing above others in quality or position"],
["arid", "(a.) extremely dry; dull, barren, unimaginative"],
["eclectic", "(a.) made from parts of various sources"],
["ubiquitous", "(a.) present everywhere"],
["ascetic", "(a.) practicing self-denial; living like a hermit"],
["contemporary", "(a.) living or happening at the same time; modern"],
["amiable", "(a.) friendly"],
["apprehensive", "(a.) fearful; aware"],
["ethereal", "(a.) exquisite, heavenly; light, airy"],
["temperate", "(a.) not extreme"],
["astute", "(a.) clever and perceptive"],
["futile", "(a.) producing no result or effect"],
["deferential", "(a.) yielding to the opinion of another"],
["trite", "(a.) commonplace; overused"],
["candid", "(a.) openly straightforward and direct"],
["didactic", "(a.) intended to instruct"],
["derisive", "(a.) showing disrespect or scorn"],
["epicurean", "(a.) devoted to sensual pleasure, escpecially in food"],
["conspicuous", "(a.) easy to see; noticeable"],
["covetous", "(a.) greedy; very desirous"],
["agrarian", "(a.) related to farming"],
["pensive", "(a.) reflective; contemplative, often with sadness"],
["communal", "(a.) with shared ownership"],
["bilateral", "(a.) affecting two sides; having two sides"],
["resilient", "(a.) flexible; capable of withstanding stress"],
["incisive", "(a.) getting to the heart of things; to the point"],
["flaccid", "(a.) limp, soft; lacking vitality"],
["beneficent", "(a.) doing good"],
["consequential", "(a.) following as an effect; important"],
["nautical", "(a.) of the sea; having to do with sailors, ships, or navigation"],
["economical", "(a.) not wasteful; thrifty"],
["cursory", "(a.) done hastily and not thoroughly"],
["indulgent", "(a.) lenient; patient; permissive"],
["provincial", "(a.) simple and plain, unsophisticated"],
["brindled", "(a.) having a streaked or patch coloring"],
["defunct", "(a.) no longer living or existing"],
["adept", "(a.) skilled; practiced"],
["contiguous", "(a.) touching; or adjoining and close, but not touching"],
["pecuniary", "(a.) relating to or involving money"],
["ambient", "(a.) in the surrounding space"],
["ambiguous", "(a.) not clear; vague"],
["evanescent", "(a.) vanishing quickly; dissipating like a vapor"],
["germane", "(a.) relevant"],
["meticulous", "(a.) exacting; precise"],
["plausible", "(a.) uncertain but seeming likely to be true"],
["wily", "(a.) concealing; sly"],
["pithy", "(a.) terse and full of meaning"],
["unequivocal", "(a.) completely clear in meaning, without room for interpretation"],
["devoid", "(a.) lacking; empty"],
["superficial", "(a.) on the surface, narrow minded; lacking depth"],
["baleful", "(a.) harmful, malign, detrimental"],
["aromatic", "(a.) giving off a pleasant smell"],
["fallible", "(a.) liable to be mistaken or erroneous"],
["ardent", "(a.) with passionate or intense feelings"],
["arduous", "(a.) difficult, requiring hard work"],
["pious", "(a.) religious; devout"],
["discreet", "(a.) showing good judgment in conduct; good at keeping secrets"],
["august", "(a.) grand, lordly; revered"],
["benign", "(a.) mild; harmless"],
["lucid", "(a.) shiny; clear-minded"],
["trivial", "(a.) unimportant; small; worthless"],
["placid", "(a.) undisturbed and calm"],
["banal", "(a.) trite; without freshness or originality"],
["audacious", "(a.) fearless, intrepid"],
["impervious", "(a.) not allowing anything to pass through; unaffected"],
["passive", "(a.) submissive; unassertive"],
["discerning", "(a.) distinguishing one thing from another; having good judgment"],
["sovereign", "(a.) independent, not ruled by another state; empowered"],
["conventional", "(a.) traditional, common, routine"],
["illusory", "(a.) lacking in or not based on reality"],
["obdurate", "(a.) stubborn"],
["diffuse", "(a.) spread out; not concise or focused"],
["assiduous", "(a.) careful and hard-working"],
["cognate", "(a.; n.) having the same family; a person related through ancestry"],
["languid", "(a.) lacking energy, moving slowly"],
["coy", "(a.) modest; bashful; pretending shyness to attract"],
["superfluous", "(a.) unnecessary; extra"],
["diminutive", "(a.) smaller than average"],
["tedious", "(a.) boring, repetitive and tiresome"],
["caustic", "(a.) harsh or corrosive"],
["destitute", "(a.) poor, living in poverty"],
["bestial", "(a.) showing a lack of human sensibility; like an animal"],
["incredulous", "(a.) skeptical"],
["cerebral", "(a.) relating to the brain; intellectual"],
["sedentary", "(a.) characterized by sitting"],
["stolid", "(a.) unemotional, not easily excited"],
["inveterate", "(a.) firmly established in a habit"],
["nebulous", "(a.) unclear or vague"],
["affable", "(a.) friendly, good-natured"],
["derogatory", "(a.) belittling; uncomplimentary"],
["sinuous", "(a.) full of curves; twisting and turning"],
["clandestine", "(a.) done secretly"],
["determinate", "(a.) having distinct limits"],
["fallacious", "(a.) misleading; based on incorrect information"],
["overweening", "(a.) arrogant; excessive"],
["stagnant", "(a.) motionless, uncirculating"],
["impetuous", "(a.) characterized by excessive haste and lack of deliberation; moving with great force and energy"],
["eccentric", "(a.) unconventional or unusual"],
["sylvan", "(a.) pertaining to or characteristic of a forest or woodland"],
["insidious", "(a.) slowly and subtly harmful"],
["laconic", "(a.) using few words"],
["onerous", "(a.) burdensome; oppressive"],
["apocryphal", "(a.) of questionable authenticity"],
["ingenuous", "(a.) innocent, naive; honest"],
["winsome", "(a.) charming"],
["ephemeral", "(a.) lasting a short time"],
["garrulous", "(a.) talking too much; wordy"],
["inchoate", "(a.) just beginning to develop; lacking structure or organization"],
["immaculate", "(a.) perfectly clean, pure; without faults"],
["prodigal", "(a.) extravagantly wasteful"],
["perfunctory", "(a.) done hastily and without attention to detail; indifferent"],
["perfidious", "(a.) intending to betray"],
["choleric", "(a.) easily angered, irascible"],
["emollient", "(a.; n.) soothing; a soothing substance"],
["pedantic", "(a.) overly concerned with formal rules and details"],
["fatuous", "(a.) stupid or foolish in a self-satisfied way"]]);

n = n.concat([["discernment", "(n.) an ability to make good judgments"],
["anomaly", "(n.) something that is unusual or unexpected"],
["travesty", "(n.) a distorted representation of something"],
["proletariat", "(n.) the working class"],
["mercenary", "(n.) a hired soldier; someone motivated only by money"],
["nadir", "(n.) the lowest point"],
["canard", "(n.) a false rumor"],
["cynosure", "(n.) the center of attraction; something that serves to guide or direct"],
["mendacity", "(n.) the tendency to be untruthful"],
["detritus", "(n.) debris or discarded material"],
["peripatetic", "(n.; a.) a worker who travels around; traveling, especially for work"],
["contusion", "(n.) a bruise; an injury where the skin is not broken"],
["raconteur", "(n.) a skilled story-teller"],
["gaucherie", "(n.) social awkwardness"],
["raiment", "(n.) clothing, garments"],
["discord", "(n.) a lack of harmony"],
["subterfuge", "(n.) something designed to deceive"],
["brevity", "(n.) shortness"],
["conceit", "(n.) an exaggerated personal opinion"],
["conciliation", "(n.) an attempt to make friendly or placate"],
["moratorium", "(n.) a suspension of an activity"],
["antagonism", "(n.) hostility; opposition"],
["curmudgeon", "(n.) an ill-tempered person"],
["epitome", "(n.) a typical example"],
["behemoth", "(n.) something that is enormous"],
["chattel", "(n.) an item of personal property that can be moved around"],
["breadth", "(n.) the distance from one side to another"],
["collusion", "(n.) secret cooperation between people"],
["facade", "(n.) a visible surface; a deceptive appearance"],
["zealot", "(n.) a believer; an enthusiast"],
["fetish", "(n.) an excessive or irrational devotion to some activity"],
["complicity", "(n.) involvement in wrongdoing"],
["hovel", "(n.) a miserable dwelling place, a shack"],
["cohort", "(n.) a group of people"],
["depravity", "(n.) moral perversion"],
["adage", "(n.) an old saying generally considered to be true"],
["amenity", "(n.) a pleasant feature or service"],
["piety", "(n.) religious devotion"],
["doldrums", "(n.) a state of depression or stagnation"],
["amalgam", "(n.) a mixture or combination"],
["altruism", "(n.) unselfish devotion to the welfare of others"],
["anarchist", "(n.) one who believes that a formal government is unnecessary"],
["probity", "(n.) complete and confirmed integrity"],
["vertigo", "(n.) the sensation of dizziness"],
["vituperation", "(n.) abusive language"],
["enigma", "(n.) a mystery"],
["connoisseur", "(n.) an expert (usually refers to a wine or food expert)"],
["philanthropist", "(n.) one who works to benefit humanity"],
["defamation", "(n.) harm of a name or reputation; slander"],
["affidavit", "(n.) a sworn written statement"],
["exigency", "(n.) urgent demand"],
["abstinence", "(n.) the act of voluntarily refraining from any action, especially sexual activity"],
["motif", "(n.) a theme"],
["talisman", "(n.) an object that serves as a charm or is believed to hold magical powers"],
["charisma", "(n.) a personal attractiveness that makes someone likeable and influential"],
["tyro", "(n.) someone new to a field or activity"],
["verbiage", "(n.) an overabundance of words"],
["utopia", "(n.) imaginary land with perfect social and political systems"],
["catalyst", "(n.) something that creates a situation in which change can occur"],
["parapet", "(n.) a low protective wall"],
["milieu", "(n.) environment or surroundings"],
["misanthrope", "(n.) a person who hates or distrusts mankind"],
["paradox", "(n.) a true statement that seems to contradict itself"],
["mores", "(n.) customary cultural standards"],
["apathy", "(n.) a lack of emotion or interest"],
["sedition", "(n.) a revolt; incitement of a revolt"],
["pittance", "(n.) a small amount of something, especially money"],
["dissonance", "(n.) musical discord; lack of harmony"],
["pique", "(n.; v.) irritation; to irritate; to arouse interest"],
["affinity", "(n.) a connection or fondness; similarity of structure"],
["glutton", "(n.) an overeater"],
["covenant", "(n.) a binding and solemn agreement"],
["eulogy", "(n.) a spoken or written tribute to a person (often a person who recently died)"],
["conclave", "(n.) a private or secret meeting"],
["cache", "(n.) a hiding place; the objects hidden in a hiding place"],
["myriad", "(n.) a large number"],
["debacle", "(n.) a disaster"],
["machination", "(n.) a crafty secret scheme; the devising of a scheme"],
["heretic", "(n.) one who holds opinion contrary to that which is generally accepted"],
["conviviality", "(n.) a fondness for festiveness"],
["aesthete", "(n.) someone who has a deep appreciation of beauty or the arts"],
["dirge", "(n.) a funeral hymn or mournful speech"],
["temerity", "(n.) fearless daring"],
["levee", "(n.) an embankment designed to prevent a river from flooding"],
["consensus", "(n.) widespread agreement"],
["exposition", "(n.) a detailed description or discussion"],
["citadel", "(n.) a fortress set up high to defend a city"],
["arbiter", "(n.) one who decides; a judge"],
["hiatus", "(n.) a break; a period of rest"],
["menagerie", "(n.) a collection of live wild animals on exhibit"],
["quarantine", "(n.) isolation of a person or persons to prevent the spread of disease"],
["abyss", "(n.) an extremely deep hole; an endless space"],
["allegory", "(n.) a symbolic description"],
["conglomeration", "(n.) a collection or mixture of various things"],
["fervor", "(n.) feelings of great intensity"],
["adjunct", "(n.) something connected or added to another; an assistant"],
["yore", "(n.) former days, an era long past"],
["lexicon", "(n.) a dictionary; the vocabulary of a particular subject"],
["partisan", "(n.) one who supports a particular cause"],
["disdain", "(n.; v.) hatred; to look down upon, to scorn"],
["litany", "(n.) a prayer or chant; a long list"],
["caprice", "(n.) a sudden unpredictable or whimsical change"],
["couture", "(n.) fashion design; fashionable clothing"],
["peregrination", "(n.) the act of traveling; an excursion"],
["anecdote", "(n.) a short personal account of an event"],
["quandary", "(n.) a state of perplexity; a difficult situation"],
["heresy", "(n.) a belief that rejects the accepted tenets of a religion"],
["acrimony", "(n.) sharpness or bitterness in language or manner"],
["husbandry", "(n.) management of resources, especially in agriculture"],
["censure", "(n.; v.) an expression of disapproval; to criticize or disapprove of"],
["cloister", "(n.) a tranquil and secluded place"],
["derision", "(n.) the act of mocking; ridicule, mockery"],
["archaism", "(n.) an old expression or practice that is no longer used"],
["deference", "(n.) courtesy, respect; submission to another person's opinion or wishes"],
["paucity", "(n.) scarcity"],
["accolade", "(n.) a sign of approval or respect"],
["accomplice", "(n.) a partner; a partner-in-crime"],
["legerdemain", "(n.) a display of cleverness, especially to deceive others"],
["potentate", "(n.) a powerful ruler; an important person"],
["debilitate", "(v.) to enfeeble; to wear out"],
["sacrilege", "(n.) improper or disrespectful treatment of something sacred"],
["idiosyncrasy", "(n.) any personal peculiarity, mannerism"],
["tableau", "(n.) a picturesque display"],
["iconoclast", "(n.) somebody who challenges established beliefs, customs, and values"],
["loquacity", "(n.) the quality of being wordy and talkative"],
["coterie", "(n.) a group of people with a common interest"],
["cacophony", "(n.) an unpleasant noise"],
["opprobrium", "(n.) a state of shame or disgrace; scorn, contempt"],
["penchant", "(n.) a strong liking"],
["pariah", "(n.) one who is rejected by a social group"],
["duress", "(n.) imprisonment; the use of threats"],
["gamin", "(n.) a child who roams the streets"],
["charlatan", "(n.) one who feigns knowledge or ability; an imposter"],
["foible", "(n.) a minor flaw or failing"],
["debutante", "(n.) a young woman being introduced to society"],
["remuneration", "(n.) a payment; the act of paying"],
["cynic", "(n.) one who distrusts human nature"],
["progeny", "(n.) descendants, offspring; followers"],
["inception", "(n.) the beginning of something"],
["blandishment", "(n.) anything designed to flatter or coax"]]);

v = v.concat([["apotheosize", "(v.) to glorify; to make into a god"],
["equivocate", "(v.) to be deliberately unclear or ambiguous"],
["discourse", "(v.) to communicate in an orderly fashion"],
["nullify", "(v.) to declare invalid"],
["forsake", "(v.) to withdraw support"],
["decamp", "(v.) to leave suddenly or secretly"],
["propitiate", "(v.) to win somebody's favor"],
["rarefy", "(v.) to make something less dense; to refine"],
["philander", "(v.) to have amorous affairs"],
["litigate", "(v.) to engage in legal proceedings"],
["proscribe", "(v.) to outlaw"],
["pillory", "(v.; n.) to punish in public; a device for public punishment"],
["winnow", "(v.) to sift through removing what is unwanted and keeping what is desirable"],
["simper", "(v.) to smile artificially"],
["hector", "(v.) to bully"],
["manifest", "(v.; a.) to appear; to show clearly; obvious"],
["atrophy", "(v.) to weaken or waste away through disuse"],
["augment", "(v.) to increase or add to; to make larger"],
["allay", "(v.) to calm someone's emotions"],
["abate", "(v.) to decrease or reduce"],
["relegate", "(v.) to move someone or something to a lower position; to banish"],
["abstain", "(v.) to choose not to do something; to not vote"],
["chafe", "(v.) to annoy, to irritate"],
["deter", "(v.) to try to prevent"],
["bolster", "(v.) to encourage or support"],
["articulate", "(v.) to express or state clearly"],
["abridge", "(v.) to shorten"],
["enthrall", "(v.) to hold spellbound"],
["revere", "(v.) to be in awe of"],
["insinuate", "(v.) to hint; to creep in"],
["renege", "(v.) to go back on one's promise or commitment"],
["obscure", "(v., a.) to make unclear; unclear, hard to understand; not important or well-known"],
["expunge", "(v.) to remove or delete"],
["discriminate", "(v.) to recognize or perceive the difference"],
["portend", "(v.) to indicate beforehand that something is about to happen"],
["consecrate", "(v.) to declare sacred; to dedicate"],
["beleaguer", "(v.) to surround or harass"],
["subsist", "(v.) to manage to remain alive"],
["adulterate", "(v.) to make something impure"],
["warrant", "(v.) to justify; to authorize"],
["codify", "(v.) to organize laws or rules into a systematic collection"],
["abhor", "(v.) to hate"],
["decry", "(v.) to denounce or condemn openly"],
["desecrate", "(v.) to violate the sacred character of a place"],
["coddle", "(v.) to treat with tenderness"],
["lament", "(v.) to express sadness or regret"],
["deride", "(v.) to laugh at with contempt; to mock"],
["coalesce", "(v.) to fuse or cause to grow together"],
["slander", "(v.) to charge falsely or with malicious intent"],
["gird", "(v.) to put a belt around; to prepare one's self"],
["allocate", "(v.) to distribute according to a plan"],
["precipitate", "(v.; a.) to bring about abruptly; done with great haste and little thought"],
["instigate", "(v.) to provoke; to stir up trouble"],
["undulate", "(v.) to move in waves"],
["digress", "(v.) to wander from a direct course"],
["amass", "(v.) to collect or gather"],
["retract", "(v.) to move back; to withdraw a statement"],
["rejuvenate", "(v.) to make more youthful or vigorous"],
["usurp", "(v.) to take something without the right to do so, especially a position of authority"],
["deign", "(v.) to do something that one considers below one's dignity"],
["gerrymander", "(v.) to manipulate the boundary of an electoral area for political gain"],
["drone", "(v.) to talk in a monotonous voice"],
["grouse", "(v.; n.) to complain; a complaint"],
["cogitate", "(v.) to think hard; to ponder"],
["dissent", "(v.) to be of a different opinion"],
["solicit", "(v.) to request insistently"],
["evince", "(v.) to display clearly; to provoke"],
["protract", "(v.) to make something last longer"],
["inveigle", "(v.) to tempt or persuade by using deception or flattery"],
["abash", "(v.) to embarass"],
["repress", "(v.) to put down by force or intimidation; to hold back feelings"],
["rivet", "(v.) to focus one's attention on something"],
["preclude", "(v.) to keep from happening"],
["alleviate", "(v.) to lessen or make easier"],
["devolve", "(v.) to pass on or delegate to another; to deteriorate"],
["excise", "(v.) to impose a tax"],
["acquiesce", "(v.) to agree without protest"],
["inculpate", "(v.) to suggest that someone is guilty"],
["postulate", "(v.; n.) to put forward a claim or assumption; an assumption or principle"],
["enrapture", "(v.) to delight or give pleasure"],
["delineate", "(v.) to outline; to describe"],
["modulate", "(v.) to regulate or adjust"],
["rescind", "(v.) to remove the validity of something"],
["meander", "(v.) to wander slowly and aimlessly"],
["accost", "(v.) to confront, especially in an aggressive way"],
["wrest", "(v.) to pull away, to take by violence"],
["bode", "(v.) to foretell something"],
["jettison", "(v.) to cast overboard; to discard"],
["facilitate", "(v.) to make easier"],
["hallow", "(v.) to make holy or sacred"],
["divert", "(v.) to change something's path"],
["sojourn", "(v.) to stay temporarily"],
["consign", "(v.) to give over to another's care"],
["raze", "(v.) to completely destroy a place"],
["imbibe", "(v.) to drink something, especially alcohol"],
["truncate", "(v.) to shorten by removing part of it"],
["peruse", "(v.) to read carefully; to study"],
["stigmatize", "(v.) to characterize or mark as disgraceful"],
["teem", "(v.) to be stocked to overflowing"],
["peculate", "(v.) to steal another's money or property"],
["ameliorate", "(v.) to improve or make better"],
["burgeon", "(v.) to grow or develop quickly"],
["heed", "(v.) to pay close attention to"],
["vindicate", "(v.) to show to be right"],
["recant", "(v.) to withdraw a previously held statement of belief"],
["deprecate", "(v.) to express disapproval of"],
["synthesize", "(v.) to combine various components into a new whole"],
["incarcerate", "(v.) to put somebody in prison"],
["placate", "(v.) to make somebody less angry"],
["refurbish", "(v.) to restore something to a better condition"],
["vilify", "(v.) to spread negative information about"],
["plumb", "(v.) to measure the depth of something"],
["mandate", "(v.) to order something officially"],
["commiserate", "(v.) to show sympathy for"],
["comport", "(v.) to behave well or properly"],
["condescend", "(v.) to treat others as socially or intellectually inferior"],
["vex", "(v.) to annoy"],
["impede", "(v.) to be a hindrance or obstacle to"],
["entreat", "(v.) to ask earnestly"],
["sanction", "(v.) to give authority or permission"],
["sanction", "(v.) to give authority or permission"],
["cavort", "(v.) to frolic"],
["confound", "(v.) to lump together, causing confusion; to damn"],
["obviate", "(v.) to do away with or make unnecessary; to prevent"],
["abdicate", "(v.) to give up a duty or a position"],
["disseminate", "(v.) to distribute or spread something, especially information"],
["conjure", "(v.) to summon; to bring into being as if by magic"],
["inculcate", "(v.) to teach by frequent repetition"],
["abscond", "(v.) to leave secretly"],
["consummate", "(v.; a.) to bring to a state of completion or perfection; complete or perfect"],
["forbear", "(v.) to not do something"],
["subjugate", "(v.) to bring somebody under the control of another"],
["occlude", "(v.) to stop up; to cut off the flow"],
["obfuscate", "(v.) to make unclear"],
["attenuate", "(v.) to make thin or slender; to weaken or lessen in intensity"],
["inure", "(v.) to cause to accept or become hardened to, to habituate"],
["corroborate", "(v.) to support with evidence or authority"],
["burnish", "(v.) to polish by rubbing"],
["pervade", "(v.) to spread throughout"],
["fleece", "(v.) to defraud or swindle"]]);

}